- type: loadout
  id: HeadofSecurityWinterGorka
  equipment:
    outerClothing: ClothingOuterWinterGorka

- type: loadout
  id: HeadofSecurityVest
  equipment:
    outerClothing: ClothingOuterArmorHoSBattleVest
